///////////////////////////////////////////////////////////
//  AtcFileHandler.cs
//  Implementation of the Class AtcFileHandler
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 10:51:17
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class AtcFileHandler : IFileHandler {

		public AtcFileHandler(){

		}

		~AtcFileHandler(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="list"></param>
		public void LogThis(List <AtcEvent> list){

		}

		/// 
		/// <param name="atcEvents"></param>
		/// <param name="logLevel"></param>
		/// <param name="msg"></param>
		public override void write(List < AtcEvent > atcEvents, LogLevel logLevel, string msg){

		}

	}//end AtcFileHandler

}//end namespace Log