///////////////////////////////////////////////////////////
//  FileFormatter.cs
//  Implementation of the Class FileFormatter
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 10:51:22
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class FileFormatter {

		public Log.LogFile m_LogFile;

		public FileFormatter(){

		}

		~FileFormatter(){

		}

		public virtual void Dispose(){

		}

	}//end FileFormatter

}//end namespace Log