///////////////////////////////////////////////////////////
//  ILog.cs
//  Implementation of the Class ILog
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 10:51:21
//  Original author: Khaled
///////////////////////////////////////////////////////////




namespace Log {
	public class ILog {

		public ILog(){

		}

		~ILog(){

		}

		public virtual void Dispose(){

		}

	}//end ILog

}//end namespace Log