///////////////////////////////////////////////////////////
//  LogFile.cs
//  Implementation of the Class LogFile
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 10:51:19
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class LogFile {

		public Log.AtcFileHandler m_AtcFileHandler;
		public Log.TracksFileHandler m_TracksFileHandler;

		public LogFile(){

		}

		~LogFile(){

		}

		public virtual void Dispose(){

		}

	}//end LogFile

}//end namespace Log