///////////////////////////////////////////////////////////
//  LogInformation.cs
//  Implementation of the Class LogInformation
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 10:51:23
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class LogInformation : ILog {

		public LogInformation(){

		}

		~LogInformation(){

		}

		public override void Dispose(){

		}

	}//end LogInformation

}//end namespace Log