///////////////////////////////////////////////////////////
//  LogLevel.cs
//  Implementation of the Class LogLevel
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 10:51:18
//  Original author: Khaled
///////////////////////////////////////////////////////////




namespace Log {
	public enum LogLevel : int {

		Warning = 0,
		Information = 1,
		Update = 2

	}//end LogLevel

}//end namespace Log