///////////////////////////////////////////////////////////
//  TracksFileHandler.cs
//  Implementation of the Class TracksFileHandler
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 10:51:20
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class TracksFileHandler : IFileHandler {

		public TracksFileHandler(){

		}

		~TracksFileHandler(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="list"></param>
		public void LogThis(List <Track> list){

		}

		/// 
		/// <param name="tracks"></param>
		/// <param name="logLevel"></param>
		/// <param name="msg"></param>
		public override void write(List < Track > tracks, LogLevel logLevel, string msg){

		}

	}//end TracksFileHandler

}//end namespace Log