///////////////////////////////////////////////////////////
//  AtcFileHandler.cs
//  Implementation of the Class AtcFileHandler
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 16:49:49
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class AtcFileHandler : IFileHandler {

		private string _logString;

		public AtcFileHandler(){

		}

		~AtcFileHandler(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="logString"></param>
		public override string LoggedItem{
			get;
			set;
		}

		/// 
		/// <param name="list"></param>
		public string LogThis(List <AtcEvent> list){

			return "";
		}

	}//end AtcFileHandler

}//end namespace Log