///////////////////////////////////////////////////////////
//  FileFormatter.cs
//  Implementation of the Class FileFormatter
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 16:49:50
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class FileFormatter {

		public FileFormatter(){

		}

		~FileFormatter(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="loggedInfo"></param>
		public string Format(LoggedInformation loggedInfo){

			return "";
		}

	}//end FileFormatter

}//end namespace Log