///////////////////////////////////////////////////////////
//  IFileHandler.cs
//  Implementation of the Class IFileHandler
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 16:49:49
//  Original author: Khaled
///////////////////////////////////////////////////////////




namespace Log {
	public class IFileHandler {

		public IFileHandler(){

		}

		~IFileHandler(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="logString"></param>
		public string LoggedItem{
			get;
			set;
		}

		/// 
		/// <param name="list"></param>
		public abstract string LogThis(List <T> list);

	}//end IFileHandler

}//end namespace Log