///////////////////////////////////////////////////////////
//  ILog.cs
//  Implementation of the Class ILog
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 16:49:50
//  Original author: Khaled
///////////////////////////////////////////////////////////




namespace Log {
	public class ILog {

		public ILog(){

		}

		~ILog(){

		}

		public virtual void Dispose(){

		}

		public IFileHandler Item{
			get;
			set;
		}

		public LogLevel logLevel{
			get;
			set;
		}

		public string Message{
			get;
			set;
		}

		public DateTimeOffset Timestamp{
			get;
			set;
		}

	}//end ILog

}//end namespace Log