///////////////////////////////////////////////////////////
//  LogInformation.cs
//  Implementation of the Class LoggedInformation
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 16:49:50
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class LoggedInformation : ILog {

		public Log.FileFormatter m_FileFormatter;

		public LoggedInformation(){

		}

		~LoggedInformation(){

		}

		public override void Dispose(){

		}

		public IFileHandler Item{
			get;
			set;
		}

		public LogLevel logLevel{
			get;
			set;
		}

		public string Message{
			get;
			set;
		}

		public DateTimeOffset Timestamp{
			get;
			set;
		}

	}//end LoggedInformation

}//end namespace Log