///////////////////////////////////////////////////////////
//  TracksFileHandler.cs
//  Implementation of the Class TracksFileHandler
//  Generated by Enterprise Architect
//  Created on:      07-apr-2013 16:49:50
//  Original author: Khaled
///////////////////////////////////////////////////////////




using Log;
namespace Log {
	public class TracksFileHandler : IFileHandler {

		private string _logString;

		public TracksFileHandler(){

		}

		~TracksFileHandler(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="logString"></param>
		public override string LoggedItem{
			get;
			set;
		}

		/// 
		/// <param name="list"></param>
		public void LogThis(List <Track> list){

		}

	}//end TracksFileHandler

}//end namespace Log